### ISSUE TITLE
회원 도메인 구현 및 엔티티 클래스 작성

### ISSUE THREAD

**Issue by pwrwpw** [threeback/kicketing-back#1]
### 📄 Describe

분석 및 설계를 바탕으로 회원 도메인을 구현하고, 엔티티 클래스 작성 예정입니다.

### ✅ Tasks

* [x] 회원 로그인, 회원 회원가입 도메인 구현
* [x] 관련 엔티티 클래스 작성

### 🙋🏻 More

# 🔥 🔥 🔥

**Comment by cottonrose1011** [comment]
🔥 🔥 🔥🔥 🔥 🔥
