### ISSUE TITLE
공연 예매 도메인 및 엔티티 클래스 작성

### ISSUE THREAD

**Issue by pwrwpw** [threeback/kicketing-back#34]
### 📄 Describe

분석 및 설계를 바탕으로 공연 예매 도메인을 구현하고, 엔티티 클래스 작성 예정입니다.

### ✅ Tasks

* [x] 공연 예매 관련 도메인 구현
* [x] 관련 엔티티 클래스 작성

### 🙋🏻 More

# 🔥 🔥 🔥

**Comment by CodingApe9** [comment]
드디어 핵심 기능 개발에 들어가네요!! 다들 파이팅입니다 😎👍
